#!/usr/bin/env bash

service_file="
[Unit]
Description=dStor IPFS
After=network.target

[Service]
Type=simple
User=$(id -un)
Group=$(id -gn)

Restart=on-failure
RestartSec=10
startLimitIntervalSec=60

WorkingDirectory=$HOME
ExecStart=$HOME/go/bin/ipfs daemon --enable-pubsub-experiment

StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=ipfs

[Install]
WantedBy=multi-user.target
"

echo service_file | sudo tee /lib/systemd/system/ipfs.service

sudo systemctl enable ipfs
sudo systemctl restart ipfs
sudo systemctl status ipfs

# Systemd
# crontab -e
echo '
If everything looks right, add your heartbeat to cron:
*/1 * * * * /usr/local/bin/outpost-cli OpHeartbeat 2>&1 | logger -t dstor-heartbeat
'
